# Numpy most important fifty commands


### 1-manipulation and creation

In [1]:
## creating 1 dimensional array 
import numpy as np
arr = np.array([1,2,3,4,4,4,5])
print(arr)

[1 2 3 4 4 4 5]


In [2]:
##creating two dimensional array
arr_2d = np.array([[1,2,3,4,5],[9,4,5,6,6]])
print(f"this is the 2d array \n {arr_2d}")

this is the 2d array 
 [[1 2 3 4 5]
 [9 4 5 6 6]]


In [3]:
## creating 2 dimensional array with no. of rows = 1 and different data types
arr_2d_diff = np.array([[1, 2, 3, 3, 4],
                        [2, 3, 46, 7, 8],
                        [5, 1, 8, 7, 9],
                        [3,5,6,7,7,]], dtype=float)
print(f"this is the 2d array with 3 rows and float data types \n {arr_2d_diff}")

this is the 2d array with 3 rows and float data types 
 [[ 1.  2.  3.  3.  4.]
 [ 2.  3. 46.  7.  8.]
 [ 5.  1.  8.  7.  9.]
 [ 3.  5.  6.  7.  7.]]


In [4]:
# creating array with zeros
arr_zeros = np.zeros((3,4))   ## np.ones and np.empty can also be used to create arrays with 1 and 0
print(f"this is the 2d array with 3 rows and 4 columns filled with zeros \n {arr_zeros}")

this is the 2d array with 3 rows and 4 columns filled with zeros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
arr_ones = np.ones((3,4))
print(f"ths the 2d array with 3rows and 4 columns filled with ones \n {arr_ones} ")

ths the 2d array with 3rows and 4 columns filled with ones 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 


In [6]:
arr_empty = np.empty((3,8))  ## creating an empty array with 3 rows and 8 columns
print(f"this is the 2d array with 3 rows and 4 columns filled with empty values \n {arr_empty} ")

this is the 2d array with 3 rows and 4 columns filled with empty values 
 [[1.07954120e-311 7.26276499e-322 0.00000000e+000 0.00000000e+000
  1.29060531e-306 1.16095484e-028 9.07236744e+223 5.28595592e-085]
 [8.96862523e-096 8.82142681e+199 1.46977911e+195 4.48324624e+174
  6.64001445e+265 2.02792954e+267 1.50110537e-153 2.31881099e-152]
 [6.60697566e+265 7.49232572e+247 9.32506541e+242 3.51446162e-152
  1.46899930e+179 9.08367237e+223 1.16466228e-028 4.71294503e+257]] 


In [7]:
## creating range and then with steps
arr_range = np.arange(10)
print(f"this is the 1d array with range of 10 \n {arr_range}")

arr_range_steps = np.arange(10, 20, 2) 
print(f"this is the 1d array with range of 10 to 20 with steps of 2 \n {arr_range_steps}")

this is the 1d array with range of 10 
 [0 1 2 3 4 5 6 7 8 9]
this is the 1d array with range of 10 to 20 with steps of 2 
 [10 12 14 16 18]


In [8]:
arr_range_step_float = np.arange(1, 8, 0.5)
print(arr_range_step_float)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]


In [9]:
arr_range_2 = np.arange(1, 20)
print(arr_range_2)  ## when giving start and end values, the end value is not included in the array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
arr_eqaul_divided = np.linspace(1, 10, 5)
print(arr_eqaul_divided)   #array is evenly divided into 5 parts from 1 to 10

[ 1.    3.25  5.5   7.75 10.  ]


In [11]:
## reshaping the array
array = np.arange(1,13)
print(f"this is the 1d array with range of 1 to 12 \n {array}")

print("--------------------------------------------------------")

arr_reshaped = array.reshape(3,4)    ###note: the total rows and columns will be equal to the total no. of elements in 1D array
print(f"this is the 2d array with 3 rows and 4 columns reshaped from the 1d array \n {arr_reshaped}")

###also do i one lines
#######array_reshaped = np.arange(1,13).reshape(3,4) 

this is the 1d array with range of 1 to 12 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
--------------------------------------------------------
this is the 2d array with 3 rows and 4 columns reshaped from the 1d array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
## convert rows into columns and columns into rows
arr = np.array([[1, 2, 3, 4 , 5],
                [5, 4, 4, 3, 2 ],
                [0, 9, 8, 7, 6]])
print(f"before transposing the array \n {arr}")

print("--------------------------------------------------------")

arr_transposed = arr.transpose()
print(f"after transposing the array \n {arr_transposed}")

before transposing the array 
 [[1 2 3 4 5]
 [5 4 4 3 2]
 [0 9 8 7 6]]
--------------------------------------------------------
after transposing the array 
 [[1 5 0]
 [2 4 9]
 [3 4 8]
 [4 3 7]
 [5 2 6]]


In [13]:
### convert multi dimensional array into 1 dimensional array, calling as flattening the array
arr_flattened = arr.flatten()
print(f"result after flattening the array \n {arr_flattened}")

result after flattening the array 
 [1 2 3 4 5 5 4 4 3 2 0 9 8 7 6]


In [14]:
# repeat the each elements of the array by given number of times
arr = np.array([1, 2, 3])
repeated_arr = np.repeat(arr, 3)  ##repeat each element of the array 3 times
print(f"original array: {arr}")
print("---------------------------------------------------------")
print(f"repeated array: {repeated_arr}")

original array: [1 2 3]
---------------------------------------------------------
repeated array: [1 1 1 2 2 2 3 3 3]


In [15]:
### repeat the array in the given n times
arr = np.array([1,2,3,4,5])
arr_tiled = np.tile(arr, 4) ## repeat the whole array 4 times
print(f"repeated_elements: {repeated_arr}")

print("--------------------------------------------------------")
print(f"repeat the whole array \n {arr_tiled}")

repeated_elements: [1 1 1 2 2 2 3 3 3]
--------------------------------------------------------
repeat the whole array 
 [1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]


# Joining, spliting and modifying the arrays

> `concatenate()` is used to join the arrays along existing axis, join array by one axis or one by one

In [16]:
arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array([6, 7, 8, 9, 10])

print(f"before concatenating tha arrys \n {arr_1} \n {arr_2}")

arr_concatenated = np.concatenate((arr_1, arr_2))
print("---------------------------------------------------------")
print(f"after concatenating the arrays \n {arr_concatenated}")

before concatenating tha arrys 
 [1 2 3 4 5] 
 [ 6  7  8  9 10]
---------------------------------------------------------
after concatenating the arrays 
 [ 1  2  3  4  5  6  7  8  9 10]


> `stacking` is the joining of two or more arrays on differenr or new axis by using the `stack()` function
> whereas, `vstack()` means stacked vertically
> `hstack()` means by existing axis which is equal to concatenation
>
> So, the concatenation is the special case o stacking
>
> But `hstack()` is used to changing the 2D or 3D into 1D, whereas `concatenate()` is only used to join the in the existing axis, does not change the dimension

In [17]:
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])

print(f"before stacking the arrays \n {arr_1} \n {arr_2}")

print("---------------------------------------------------------")

arr_stacked = np.stack([arr_1, arr_2])   ## by default it stack vertically
print(f"after stacking the arrays \n {arr_stacked}")

before stacking the arrays 
 [1 2 3 4 5] 
 [ 6  7  8  9 10]
---------------------------------------------------------
after stacking the arrays 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [18]:
arr_horizontally_stacked = np.hstack((arr_1, arr_2)) ## stack horizontally
print("---------------------------------------------------------")
print(f"after horizontally stacking the arrays \n {arr_horizontally_stacked}")

print("---------------------------------------------------------")
arr_vertically_stacked = np.vstack((arr_1, arr_2)) ## stack vertically
print(f"after vertically stacking the arrays \n {arr_vertically_stacked}")

---------------------------------------------------------
after horizontally stacking the arrays 
 [ 1  2  3  4  5  6  7  8  9 10]
---------------------------------------------------------
after vertically stacking the arrays 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
## split array into multiple sub-arrays, but divided into equal parts
array = np.array([1,2,3,4,5,6,7,8,9,0])
sub_arrays = np.split(array, 5)  ## split the array into 5 equal parts
print(f"original array: {array}")

print("---------------------------------------------------------")
print(f"sub_arrays; \n {sub_arrays}")

original array: [1 2 3 4 5 6 7 8 9 0]
---------------------------------------------------------
sub_arrays; 
 [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9, 0])]


In [20]:
### delete the elements of the array, in giving index range
arr = np.array([1,2,3,4,5,6,7,9])
arr_deleted = np.delete(arr, 7) ## delete at index 7
print(f"original array \n {arr}")

print("--------------------------------------------------------")
print(f"deleted the elment at index 7 \n {arr_deleted}")


original array 
 [1 2 3 4 5 6 7 9]
--------------------------------------------------------
deleted the elment at index 7 
 [1 2 3 4 5 6 7]


In [21]:
##delete the multiple elements of array
arr_multi_deleted = np.delete(arr, [1,2,3])
print(f"original array \n {arr}")

print("--------------------------------------------------------")
print(f"deleted the multiple elements at index 1,2 3 \n {arr_multi_deleted}")

original array 
 [1 2 3 4 5 6 7 9]
--------------------------------------------------------
deleted the multiple elements at index 1,2 3 
 [1 5 6 7 9]


In [22]:
##deleted the elements of two dimensional array
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_2d_deleted = np.delete(arr_2d, 1, axis =0)  ## delete the row at index 1, axis = 1 means row and axis = 0 means column
print(f"original arr_2d \n {arr_2d}")
print("-------------------------------------------------------")
print(f"deleted the row at index 1 \n {arr_2d_deleted}")


original arr_2d 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-------------------------------------------------------
deleted the row at index 1 
 [[1 2 3 4 5]]


In [23]:
###indexing of arrays
arr = np.array([1,2,3,45,5,6,7,8,9])
print(f"original array \n {arr}")
print("-------------------------------------------------------")
print(f"indexing at 3 index : {arr[3]}")
print(f"indexing at -3 index : {arr[-3]}")

original array 
 [ 1  2  3 45  5  6  7  8  9]
-------------------------------------------------------
indexing at 3 index : 45
indexing at -3 index : 7


In [24]:
### slicing of arrays
arr = np.array([1,2,3,4,5,6,6,7,7,5])
print(f"original array \n {arr}")
print("--------------------------------------------------------" )
sliced_arr = arr[2:8]  ## slicing from index 2 to 7, the end index is not included
print(f"after slicing \n {sliced_arr}")

original array 
 [1 2 3 4 5 6 6 7 7 5]
--------------------------------------------------------
after slicing 
 [3 4 5 6 6 7]


In [25]:
##slicing of 2 dimensional array
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(f"original 2d array \n {arr_2d}")
print("-------------------------------------------------------")
sliced_arr_2d = arr_2d[1:3, 1:3]  ## slicing from index 1 to 3 and 1 to 3, the end index is not included
print(f"after slicing \n {sliced_arr_2d}")

original 2d array 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-------------------------------------------------------
after slicing 
 [[7 8]]


In [26]:
## insert the elements into the array at given n index
arr = np.array([1,2,3,4,5])
print(f"originl array \n {arr}")

print("--------------------------------------------------------")
inserted_arr = np.insert(arr, 2, 6) ## insert 6 at index 2
print(f"after inserting 6 at index 2 \n {inserted_arr}")

## add element at last by append()
appended_arr = np.append(arr, 6)  ## append 6 at the end of the array
print("-----------------------------------------------------------")
print(f"after appending the array \n {appended_arr}")

##updating the array elements by given n index
arr[0] = 6  ## also can be used to update the element at index 2 with 6
print("-----------------------------------------------------------")
print(f"after updating the array \n {arr}") 

originl array 
 [1 2 3 4 5]
--------------------------------------------------------
after inserting 6 at index 2 
 [1 2 6 3 4 5]
-----------------------------------------------------------
after appending the array 
 [1 2 3 4 5 6]
-----------------------------------------------------------
after updating the array 
 [6 2 3 4 5]


# Mathematical operation

In [27]:
## Arithmetic operations on array
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,0])

#add
arr_add = arr_1 + arr_2
print(f"addition of arrays \n {arr_add}")
print("---------------------------------------------------------")
arr_sub = arr_1 - arr_2
print(f"subtraction of arrays \n {arr_sub}")
print("---------------------------------------------------------")
arr_mul = arr_1 * arr_2
print(f"multiplication of arrays \n {arr_mul}")
print("---------------------------------------------------------")
arr_div = arr_1 / arr_2
print(f"division of arrays \n {arr_div}")

##power of arrays
arr_power = arr_1**2
print("---------------------------------------------------------")
print(f"power of arrays \n {arr_power}")

## square root of arrays
arr_sqrt = np.sqrt(arr_power)
print("---------------------------------------------------------")
print(f"sqaure root of arrays \n {arr_sqrt}")  ## ans in float, if want in int, use arr_sqrt.astype(int)

# exopenential of arrays
arr_exp = np.exp(arr_1)
print("---------------------------------------------------------")
print(f"exponential of arrays \n {arr_exp}") 


addition of arrays 
 [ 7  9 11 13  5]
---------------------------------------------------------
subtraction of arrays 
 [-5 -5 -5 -5  5]
---------------------------------------------------------
multiplication of arrays 
 [ 6 14 24 36  0]
---------------------------------------------------------
division of arrays 
 [0.16666667 0.28571429 0.375      0.44444444        inf]
---------------------------------------------------------
power of arrays 
 [ 1  4  9 16 25]
---------------------------------------------------------
sqaure root of arrays 
 [1. 2. 3. 4. 5.]
---------------------------------------------------------
exponential of arrays 
 [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


C:\Users\mhusm\AppData\Local\Temp\ipykernel_2888\3997003840.py:15: RuntimeWarning: divide by zero encountered in divide
  arr_div = arr_1 / arr_2


In [28]:
##a taking log of arrays, usaully used in data science for feature engineering, normalization or scalling the data
arr = np.array([100, 200, 1000000])
arr_log = np.log(arr)
print(f"original array \n {arr}")
print("---------------------------------------------------------")
print(f"after taking log \n {arr_log}")


original array 
 [    100     200 1000000]
---------------------------------------------------------
after taking log 
 [ 4.60517019  5.29831737 13.81551056]


In [29]:
## mathematical constant
eular_constant = print(f" eular_constant: {np.e}")
pi = print(f" pi_constant: {np.pi}")

 eular_constant: 2.718281828459045
 pi_constant: 3.141592653589793


In [30]:
## random number
rand_num = np.random.rand()
print(rand_num)

0.12952178993238372
