# Numpy most important fifty commands


### 1-manipulation and creation

In [1]:
## creating 1 dimensional array 
import numpy as np
arr = np.array([1,2,3,4,4,4,5])
print(arr)

[1 2 3 4 4 4 5]


In [2]:
##creating two dimensional array
arr_2d = np.array([[1,2,3,4,5],[9,4,5,6,6]])
print(f"this is the 2d array \n {arr_2d}")

this is the 2d array 
 [[1 2 3 4 5]
 [9 4 5 6 6]]


In [ ]:
## creating 2 dimensional array with no. of rows = 1 and different data types
arr_2d_diff = np.array([[1, 2, 3, 3, 4],
                        [2, 3, 46, 7, 8],
                        [5, 1, 8, 7, 9],
                        [3,5,6,7,7,]], dtype=float)
print(f"this is the 2d array with 3 rows and float data types \n {arr_2d_diff}")

this is the 2d array with 3 rows and float data types 
 [[ 1.  2.  3.  3.  4.]
 [ 2.  3. 46.  7.  8.]
 [ 5.  1.  8.  7.  9.]
 [ 3.  5.  6.  7.  7.]]


In [4]:
# creating array with zeros
arr_zeros = np.zeros((3,4))   ## np.ones and np.empty can also be used to create arrays with 1 and 0
print(f"this is the 2d array with 3 rows and 4 columns filled with zeros \n {arr_zeros}")

this is the 2d array with 3 rows and 4 columns filled with zeros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
arr_ones = np.ones((3,4))
print(f"ths the 2d array with 3rows and 4 columns filled with ones \n {arr_ones} ")

ths the 2d array with 3rows and 4 columns filled with ones 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 


In [ ]:
arr_empty = np.empty((3,8))  ## creating an empty array with 3 rows and 8 columns
print(f"this is the 2d array with 3 rows and 4 columns filled with empty values \n {arr_empty} ")

this is the 2d array with 3 rows and 4 columns filled with empty values 
 [[1.23453322e-311 7.65801751e-322 0.00000000e+000 0.00000000e+000
  5.95850636e-292 1.16096346e-028 9.82205649e+252 1.11789342e+253]
 [8.88254275e+247 1.27734658e-152 4.83245960e+276 1.42652654e-153
  6.01099964e+175 1.89063981e+219 3.68574020e+180 1.32979220e+179]
 [1.17567374e+214 9.11159886e+130 4.57890143e-072 1.81152934e-152
  4.57890143e-072 1.81152934e-152 4.57890143e-072 5.94724995e+135]] 


In [5]:
## creating range and then with steps
arr_range = np.arange(10)
print(f"this is the 1d array with range of 10 \n {arr_range}")

arr_range_steps = np.arange(10, 20, 2) 
print(f"this is the 1d array with range of 10 to 20 with steps of 2 \n {arr_range_steps}")

this is the 1d array with range of 10 
 [0 1 2 3 4 5 6 7 8 9]
this is the 1d array with range of 10 to 20 with steps of 2 
 [10 12 14 16 18]


In [11]:
arr_range_step_float = np.arange(1, 8, 0.5)
print(arr_range_step_float)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]


In [ ]:
arr_range_2 = np.arange(1, 20)
print(arr_range_2)  ## when giving start and end values, the end value is not included in the array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
arr_eqaul_divided = np.linspace(1, 10, 5)
print(arr_eqaul_divided)   #array is evenly divided into 5 parts from 1 to 10

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
## reshaping the array
array = np.arange(1,13)
print(f"this is the 1d array with range of 1 to 12 \n {array}")

print("--------------------------------------------------------")

arr_reshaped = array.reshape(3,4)    ###note: the total rows and columns will be equal to the total no. of elements in 1D array
print(f"this is the 2d array with 3 rows and 4 columns reshaped from the 1d array \n {arr_reshaped}")

###also do i one lines
#######array_reshaped = np.arange(1,13).reshape(3,4) 

this is the 1d array with range of 1 to 12 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
--------------------------------------------------------
this is the 2d array with 3 rows and 4 columns reshaped from the 1d array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
## convert rows into columns and columns into rows
arr = np.array([[1, 2, 3, 4 , 5],
                [5, 4, 4, 3, 2 ],
                [0, 9, 8, 7, 6]])
print(f"before transposing the array \n {arr}")

print("--------------------------------------------------------")

arr_transposed = arr.transpose()
print(f"after transposing the array \n {arr_transposed}")

before transposing the array 
 [[1 2 3 4 5]
 [5 4 4 3 2]
 [0 9 8 7 6]]
--------------------------------------------------------
after transposing the array 
 [[1 5 0]
 [2 4 9]
 [3 4 8]
 [4 3 7]
 [5 2 6]]


In [18]:
### convert multi dimensional array into 1 dimensional array, calling as flattening the array
arr_flattened = arr.flatten()
print(f"result after flattening the array \n {arr_flattened}")

result after flattening the array 
 [1 2 3 4 5 5 4 4 3 2 0 9 8 7 6]


In [ ]:
# repeat the each elements of the array by given number of times
arr = np.array([1, 2, 3])
repeated_arr = np.repeat(arr, 3)  ##repeat each element of the array 3 times
print(f"original array: {arr}")
print("---------------------------------------------------------")
print(f"repeated array: {repeated_arr}")

original array: [1 2 3]
---------------------------------------------------------
repeated array: [1 1 1 2 2 2 3 3 3]


# Joining, spliting and modifying the arrays

> `concatenated` is used to join the arrays along existing axis

In [20]:
arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array([6, 7, 8, 9, 10])

print(f"before concatenating the arrays \n {arr_1} \n {arr_2}")

arr_concatenated = np.concatenate((arr_1, arr_2))
print("---------------------------------------------------------")
print(f"after concatenating the arrays \n {arr_concatenated}")

NameError: name 'aar_1' is not defined